# Veynor one-line installer (Windows PowerShell)
#
# Usage:
#   irm https://raw.githubusercontent.com/daryhh/veynor/main/scripts/install.ps1 | iex
#
#   Or with overrides:
#   powershell -ExecutionPolicy Bypass -File install.ps1 -Ref v0.1.0 -Dir C:\veynor
#
# What it does:
#   1. Verifies Node.js >= 22
#   2. Installs pnpm via corepack (built into Node 16+)
#   3. Clones the Veynor repo (or pulls if already present)
#   4. Runs pnpm install + pnpm build
#   5. Adds the veynor command to your PATH
#
param(
  [string]$RepoUrl = "https://github.com/daryhh/veynor.git",
  [string]$Ref     = "main",
  [string]$Dir     = "$env:USERPROFILE\.veynor",
  [switch]$NoLink
)

$ErrorActionPreference = "Stop"

# ── 1. Node.js check ─────────────────────────────────────────
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
  Write-Error "Node.js is not installed. Get it from https://nodejs.org/ (>= 22)"
  exit 1
}
$nodeVer = & node -v
$nodeMajor = [int]($nodeVer -replace '^v(\d+)\..*', '$1')
if ($nodeMajor -lt 22) {
  Write-Error "Veynor needs Node.js >= 22. You have $nodeVer"
  exit 1
}
Write-Host "✓ Node.js $nodeVer" -ForegroundColor Green

# ── 2. pnpm via corepack ─────────────────────────────────────
$pnpmCmd = Get-Command pnpm -ErrorAction SilentlyContinue
if (-not $pnpmCmd) {
  Write-Host "→ Installing pnpm via corepack..." -ForegroundColor Cyan
  corepack enable
  corepack prepare pnpm@9 --activate
}
Write-Host "✓ pnpm $(pnpm -v)" -ForegroundColor Green

# ── 3. Clone or pull ─────────────────────────────────────────
if (Test-Path $Dir) {
  Write-Host "→ $Dir already exists, pulling latest..." -ForegroundColor Cyan
  Push-Location $Dir
  try { git pull --ff-only } catch { Write-Host "  (pull failed, continuing)" }
  Pop-Location
} else {
  Write-Host "→ Cloning Veynor to $Dir..." -ForegroundColor Cyan
  git clone --depth 1 --branch $Ref $RepoUrl $Dir
}

# ── 4. Install + build ────────────────────────────────────────
Set-Location $Dir
Write-Host "→ pnpm install..." -ForegroundColor Cyan
pnpm install
Write-Host "→ pnpm build..." -ForegroundColor Cyan
pnpm build

# ── 5. Add veynor to PATH ───────────────────────────────────
if (-not $NoLink) {
  $bin = "$env:USERPROFILE\.local\bin"
  if (-not (Test-Path $bin)) {
    New-Item -ItemType Directory -Force -Path $bin | Out-Null
  }
  $wrapper = "$bin\veynor.cmd"
  @"
@echo off
REM Auto-generated by veynor installer
node "$Dir\bin\veynor.js" %*
"@ | Set-Content -Path $wrapper -Encoding UTF8

  # Add to user PATH if not already there
  $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
  if ($userPath -notlike "*$bin*") {
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$bin", "User")
    Write-Host "✓ Added $bin to user PATH. Restart your terminal." -ForegroundColor Green
  }
  Write-Host "✓ Installed veynor wrapper at $wrapper" -ForegroundColor Green
}

Write-Host ""
Write-Host "✓ Veynor installed at $Dir" -ForegroundColor Green
Write-Host ""
Write-Host "  Next:"
Write-Host "    cd $Dir"
Write-Host "    veynor                 # first run: setup wizard -> start bot"
Write-Host "    veynor doctor          # verify all components"
Write-Host ""
