#!/usr/bin/env bash
# Veynor one-line installer (Unix/macOS/WSL/git-bash)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/daryhh/veynor/main/scripts/install.sh | bash
#
#   Or with overrides:
#   bash install.sh --ref v0.1.0 --dir ~/.veynor --no-link
#
# What it does:
#   1. Verifies Node.js ≥ 22
#   2. Installs pnpm via corepack (no separate install needed)
#   3. Clones the Veynor repo (or pulls if already present)
#   4. Runs pnpm install + pnpm build
#   5. Symlinks `veynor` into ~/.local/bin (skip with --no-link)
#
set -e

REPO_URL="https://github.com/daryhh/veynor.git"
REF="main"
DIR="$HOME/.veynor"
LINK=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref)  REF="$2"; shift 2 ;;
    --dir)  DIR="$2"; shift 2 ;;
    --url)  REPO_URL="$2"; shift 2 ;;
    --no-link) LINK=false; shift ;;
    -h|--help)
      echo "Usage: bash install.sh [--ref REF] [--dir DIR] [--url URL] [--no-link]"
      exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# ── 1. Node.js check ─────────────────────────────────────────
if ! command -v node &> /dev/null; then
  echo "✗ Node.js is not installed."
  echo "  Install via: https://nodejs.org/  (or use nvm: nvm install 22)"
  exit 1
fi
NODE_MAJOR=$(node -v | sed -E 's/^v([0-9]+).*/\1/')
if [ "$NODE_MAJOR" -lt 22 ]; then
  echo "✗ Veynor needs Node.js ≥ 22. You have $(node -v)"
  echo "  Try: nvm install 22 && nvm use 22"
  exit 1
fi
echo "✓ Node.js $(node -v)"

# ── 2. pnpm via corepack (built into Node 16+) ────────────────
if ! command -v pnpm &> /dev/null; then
  echo "→ Installing pnpm via corepack..."
  corepack enable
  corepack prepare pnpm@9 --activate
fi
echo "✓ pnpm $(pnpm -v)"

# ── 3. Clone or pull ──────────────────────────────────────────
if [ -d "$DIR" ]; then
  echo "→ $DIR already exists, pulling latest..."
  (cd "$DIR" && git pull --ff-only || echo "  (pull failed, continuing with existing tree)")
else
  echo "→ Cloning Veynor to $DIR..."
  git clone --depth 1 --branch "$REF" "$REPO_URL" "$DIR"
fi

# ── 4. Install + build ────────────────────────────────────────
cd "$DIR"
echo "→ pnpm install..."
pnpm install
echo "→ pnpm build..."
pnpm build

# ── 5. Symlink the `veynor` binary ───────────────────────────
if [ "$LINK" = true ]; then
  BIN_DIR="$HOME/.local/bin"
  mkdir -p "$BIN_DIR"
  # Use a small wrapper script so the symlink works on Windows too
  # (where bin/veynor.js needs `node` to run).
  WRAPPER="$BIN_DIR/veynor"
  cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by veynor installer
exec node "$DIR/bin/veynor.js" "\$@"
EOF
  chmod +x "$WRAPPER"
  echo "✓ Linked $WRAPPER"

  # PATH hint
  if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    SHELL_RC="$HOME/.$(basename "$SHELL")rc"
    echo ""
    echo "  Add to your PATH by adding this line to $SHELL_RC:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo "  Then restart your shell or:  source $SHELL_RC"
  fi
fi

echo ""
echo "✓ Veynor installed at $DIR"
echo ""
echo "  Next:"
echo "    cd $DIR"
echo "    veynor                 # first run: setup wizard → start bot"
echo "    veynor doctor          # verify all components"
echo ""
